# Practical_6: Numpy

---

### Exercise 1:
Create a NumPy array of integers from 1 to 10.

```python

```

---

In [139]:
import numpy as np
v = np.arange(1,11) # arange function generates values from 1 to 10
v

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

### Exercise 2:
Create a 3x3 NumPy array filled with zeros.

```python

```

---

In [140]:
z=np.zeros((3,3)) # the zeros function generates 3x3 0 matrix
z

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

### Exercise 3:
Create a NumPy array of 10 evenly spaced numbers between 0 and 5.

```python

```

---

In [11]:
E=np.linspace(0,5,10) # the linspace function generates 10 numbers from 1 to 5 inclusive evenly spaced
E

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

### Exercise 4:
Create a 5x5 identity matrix using NumPy.

```python
```

---

In [13]:
I = np.eye(5) # the eye function generates the identity matrix
I

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

### Exercise 5:
Create a 4x4 matrix with random values between 0 and 1.

```python

```

---

In [141]:
r = np.random.random((4,4)) # random.random generates values between 0 and 1
r

array([[0.21539438, 0.89619905, 0.61520964, 0.27077379],
       [0.60622767, 0.25218489, 0.36004503, 0.65780996],
       [0.67339576, 0.03237536, 0.68145225, 0.55951188],
       [0.18514895, 0.34946007, 0.57420104, 0.78546893]])

### Exercise 6:
Find the shape of a NumPy array.

```python

```

---

In [17]:
s = np.array([[1,2,3],[4,5,6],[7,9,4]]) 

print(s.shape)

(3, 3)


### Exercise 7:
Reshape a 1D NumPy array of 16 elements into a 4x4 matrix.

```python
```

---

In [21]:
v = np.arange(16)
v
v_s = v.reshape((4,4)) # the reshape function changes the 1D array to 4x4 matrix
v_s

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

### Exercise 8:
Find the data type of the elements in a NumPy array.

```python

```

---


In [23]:
v_s.dtype


dtype('int64')

### Exercise 9:
Create a NumPy array of integers from 1 to 100 and find all even numbers in the array.

```python

```

---

In [26]:
v = np.arange(1,101)
even=v[(v%2==0)] #filters out all the even elements in the array
even

array([  2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,  26,
        28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,  52,
        54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,  78,
        80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

### Exercise 10:
Generate a 6x6 matrix of random integers between 10 and 50.

```python

```

---

In [142]:
M = np.random.randint(10,50,size=(6,6)) #use random.randint to generate random integers for the 6x6 matrix
M

array([[45, 14, 21, 38, 45, 24],
       [38, 21, 33, 42, 28, 12],
       [27, 37, 34, 13, 44, 35],
       [16, 33, 39, 10, 21, 39],
       [24, 18, 21, 18, 43, 23],
       [32, 35, 10, 19, 34, 23]])

### Exercise 11:
Slice a 2D NumPy array to extract a submatrix.

```python

```

---

In [147]:
v=np.random.randint(25,size=(4,3))
w=v[1,] #slice a 3X1 
print(w)

[ 6 17  7]


### Exercise 12:
Calculate the sum of all elements in a NumPy array.

```python

```

---


In [150]:
v=np.random.randint(25,size=(4,3))
np.sum(v)#

157

### Exercise 13:
Calculate the mean, median, and standard deviation of a NumPy array.

```python

```

---

In [151]:
print(np.mean(v))
print(np.median(v))
print(np.std(v))

#gives the global,mean median and std


13.083333333333334
14.5
4.192420409368422


### Exercise 14:
Find the maximum and minimum values in a NumPy array.

```python

```

---

In [152]:
print(np.max(v))
print(np.min(v))


19
4


In [154]:
print(np.max(v))
print(np.min(v))

19
4


### Exercise 15:
Create a NumPy array of 20 random integers and find the index of the maximum value.

```python
```

---

In [156]:
x = np.random.randint(21,size=(1,20))
print(x)
print("")
print(np.argmax(x)) #argmax function gives index of max value


[[ 7 10 12  4 19  1  6  3  8 15  8  2  4  5 16  0 10  9 16 18]]

4


### Exercise 16:
Create a NumPy array and reverse its elements.

```python

```

---

In [157]:
y = np.arange(1,20,2)
print(np.flip(y))

[19 17 15 13 11  9  7  5  3  1]


### Exercise 17:
Create a 3x3 matrix and multiply it element-wise by another 3x3 matrix.

```python

```

---

In [57]:
x = np.random.randint(10,size=(3,3))
print(x)
y=np.random.randint(10,size=(3,3))
print(y)
print("")
z=x*y
print(z)

[[5 1 5]
 [3 2 6]
 [1 6 2]]
[[1 3 6]
 [3 6 4]
 [9 7 3]]

[[ 5  3 30]
 [ 9 12 24]
 [ 9 42  6]]


### Exercise 18:
Create a diagonal matrix from a given 1D array.

```python
```

---

In [158]:
d = np.arange(1,6)
D= np.diag(d)#the diag fxn generates the random number the array d
print(D) 

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


### Exercise 19:
Perform matrix multiplication on two 2D NumPy arrays.

```python
```

---

In [160]:
x = np.random.randint(10,size=(2,3))
y = np.random.randint(10,size=(3,2))

print(np.dot(x,y))# use dot function for matrix multiply

[[71 35]
 [93 71]]


### Exercise 20:
Flatten a 2D NumPy array into a 1D array.

```python

```

---

In [161]:
x = np.random.randint(10,size=(3,2))

x.flatten()# faltten function to turn the 2D array x to 1D

array([0, 9, 1, 8, 4, 1])

### Exercise 21:
Stack two NumPy arrays vertically.

```python


```

---

In [163]:
x = np.random.randint(10,size=(2,3))
y = np.random.randint(10,size=(2,3))

np.vstack((x,y)) #stacks matrix x  vertically on matrix y

array([[3, 4, 1],
       [9, 8, 0],
       [4, 3, 7],
       [7, 2, 0]])

### Exercise 22:
Stack two NumPy arrays horizontally.

```python

```

---

In [162]:
np.hstack((x,y)) #stacks matrix x  horizontally to matrix y

array([[0, 9, 6, 1],
       [1, 8, 5, 6],
       [4, 1, 3, 5]])

### Exercise 23:
Split a NumPy array into multiple sub-arrays.

```python

```

---

In [164]:
a = np.random.randint(10,size=(6,6))

b= np.split(a,6) #splitting into 6 arrays
print(b)
print("")
print(np.hsplit(a,3)) #splitting horizontally into 3 arrays
print("")
print(np.vsplit(a,3)) #splitting horizontally into 3 arrays

[array([[0, 4, 2, 0, 4, 8]]), array([[8, 3, 4, 3, 4, 9]]), array([[9, 7, 6, 1, 5, 8]]), array([[9, 9, 2, 2, 8, 0]]), array([[4, 7, 6, 8, 2, 4]]), array([[4, 7, 8, 2, 2, 4]])]

[array([[0, 4],
       [8, 3],
       [9, 7],
       [9, 9],
       [4, 7],
       [4, 7]]), array([[2, 0],
       [4, 3],
       [6, 1],
       [2, 2],
       [6, 8],
       [8, 2]]), array([[4, 8],
       [4, 9],
       [5, 8],
       [8, 0],
       [2, 4],
       [2, 4]])]

[array([[0, 4, 2, 0, 4, 8],
       [8, 3, 4, 3, 4, 9]]), array([[9, 7, 6, 1, 5, 8],
       [9, 9, 2, 2, 8, 0]]), array([[4, 7, 6, 8, 2, 4],
       [4, 7, 8, 2, 2, 4]])]


### Exercise 24:
Generate a random NumPy array and round each element to two decimal places.

```python

```

---

In [91]:
a = np.random.rand(10)
np.round(a,2)


array([0.27, 0.34, 0.42, 0.21, 0.8 , 0.22, 0.73, 0.47, 0.36, 0.71])

### Exercise 25:
Find the unique elements of a NumPy array.

```python
```

---

In [98]:
s = np.array([[1,2,3],[2,5,1],[7,3,4]]) 

print(np.unique(s))

[1 2 3 4 5 7]


### Exercise 26:
Replace all elements in a NumPy array that are less than a specific value with that value.

```python
```

---

In [101]:
s = np.array([[1,2,3],[4,5,6],[7,9,4]]) 
s[s<=5]=5 # set all the values <5 in the array to 5
new_s=s
print(new_s)

[[5 5 5]
 [5 5 6]
 [7 9 5]]


### Exercise 27:
Find the cumulative sum of the elements in a NumPy array.

```python

```

---

In [103]:
a = np.random.randint(12,size=(4,3))
print(a)
print("")
np.cumsum(a)

[[ 2  1  9]
 [ 9 11  4]
 [11  4  4]
 [ 5 10  8]]



array([ 2,  3, 12, 21, 32, 36, 47, 51, 55, 60, 70, 78])

### Exercise 28:
Create a NumPy array and find the number of non-zero elements in it.

```python
```

---

In [108]:
a = np.random.randint(12,size=(4,3))
print(a)
print(np.count_nonzero(a))

[[ 2  0 10]
 [ 5  0  3]
 [ 0 11  1]
 [ 2  7  0]]
8


### Exercise 29:
Create a NumPy array of random integers and sort it in ascending order.

```python
```

---

In [166]:
a = np.random.randint(12,size=(4,3))
print(a)
print("")
print(np.sort(a))

[[ 3  3  2]
 [ 7  3 10]
 [ 4  9  9]
 [10 11  4]]

[[ 2  3  3]
 [ 3  7 10]
 [ 4  9  9]
 [ 4 10 11]]


### Exercise 30:
Find the row-wise and column-wise sum of a 3x3 matrix.

```python
```

---

In [113]:
a = np.random.randint(12,size=(4,3))
print(np.sum(a,axis=1))#row wise
print(np.sum(a,axis=0))#column wise

[20 12  5 21]
[18 10 30]


### Exercise 31:
Generate a 2D NumPy array with random values and normalize it (scale the values between 0 and 1).

```python

```

---

In [119]:
a = np.random.randint(12,size=(3,3))
print(a)
norm_a=(a - np.min(a))/(np.max(a)-np.min(a))#equation of normalization
print("")
print(norm_a)

[[ 9  8 10]
 [ 2  7  8]
 [ 0  9  7]]

[[0.9 0.8 1. ]
 [0.2 0.7 0.8]
 [0.  0.9 0.7]]


### Exercise 32:
Create two NumPy arrays and find the dot product.

```python
```

---

In [120]:
a = np.random.randint(12,size=(3,3))
b = np.random.randint(12,size=(3,3))

print(np.dot(a,b))

[[132  71 130]
 [ 60  48  84]
 [ 47  13  25]]


### Exercise 33:
Find the trace of a square NumPy matrix.

```python

```

---

In [167]:
a = np.random.randint(15,size=(4,4))
np.trace(a)

17

### Exercise 34:
Create a 2D array and swap two rows.

```python
```

---

In [125]:
a = np.random.randint(15,size=(4,3))

print(a)
print("")
a[[0,1]]=a[[1,0]] #swap row 1 and row 2

print(a)

[[14  1 11]
 [13  2 11]
 [ 6  1  1]
 [ 5 11 13]]

[[13  2 11]
 [14  1 11]
 [ 6  1  1]
 [ 5 11 13]]


### Exercise 35:
Create a 1D NumPy array and convert it into a column vector.

```python

```

---

In [173]:
w = np.arange(7)

c = np.reshape(w,(-1,1))
print(c)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]]


### Exercise 36:
Find the determinant of a 3x3 matrix.

```python

```

---

In [175]:
d = np.random.randint(12,size=(3,3))
np.linalg.det(d)

225.0

### Exercise 37:
Find the eigenvalues and eigenvectors of a 2x2 matrix.

```python

```

---

In [131]:
d = np.random.randint(12,size=(2,2))
np.linalg.eig(d)

(array([11.,  1.]),
 array([[ 0.70710678, -0.3939193 ],
        [ 0.70710678,  0.91914503]]))

### Exercise 38:
Solve a system of linear equations using NumPy.

```python

```

---

In [176]:
#solving the equation a+2b+3c=9, 2a+3b+c=8, 3a+b+2c=7 
x = np.array([[1,2,3],[2,3,1],[3,1,2]]) # coefficient matrix
y=[9,8,7] #constant matrix
z = np.linalg.solve(x,y) #solution vector
z

array([0.66666667, 1.66666667, 1.66666667])

### Exercise 39:
Add Gaussian noise to a NumPy array.

```python
# Exercise 39
```

---

In [177]:
a = np.random.randint(12,size=(3,3))
noise = np.random.normal(0,1,len(a)) #generating noise with mean 0 and standard deviation 1(standard normal distribution)

a_noise=a+noise #adding noise to array

a_noise

array([[-0.29208741,  2.38439557,  1.75511794],
       [ 1.70791259,  4.38439557,  7.75511794],
       [ 8.70791259, 11.38439557,  0.75511794]])

### Exercise 40:
Create a 4x4 matrix and extract the diagonal elements.

```python

```

---

In [178]:
d = np.random.randint(12,size=(4,4))
print(np.diag(d))# access the diagonal elements of the 4x4 matrix

[10  0  2  7]


### Exercise 41:
Generate a NumPy array of 100 random values and clip the values to a range between 10 and 50.

```python
# Exercise 41
```

---

### Exercise 42:
Create a 2D NumPy array and replace all negative values with zero.

```python
# Exercise 42
```

---

### Exercise 43:
Find the inner and outer products of two NumPy arrays.

```python
# Exercise 43
```

---

### Exercise 44:
Calculate the pairwise distances between points in a NumPy array.

```python
# Exercise 44
```

---

### Exercise 45:
Create a structured NumPy array with fields for `name`, `age`, and `height`.

```python
# Exercise 45
```

---

### Exercise 46:
Create a 5x5 matrix of random integers and count the occurrences of each unique value.

```python
# Exercise 46
```

---

### Exercise 47:
Generate a random 3x3 NumPy array and subtract the mean of each row from the corresponding row.

```python
# Exercise 47
```

---

### Exercise 48:
Create a NumPy array of random integers and check if any of the values are greater than 50.

```python
# Exercise 48
```

---

### Exercise 49:
Calculate the moving average of a 1D NumPy array.

```python
# Exercise 49
```

---

### Exercise 50:
Find the Pearson correlation coefficient between two NumPy arrays.

```python
# Exercise 50
```

---

### Exercise 51:
Convert a NumPy array of radians to degrees.

```python
# Exercise 51
```

---

### Exercise 52:
Create a random NumPy array and compute its variance and standard deviation.

```python
# Exercise 52
```

---

### Exercise 53:
Create a 2D NumPy array and find the indices of the maximum values along each axis.

```python
# Exercise 53
```

---

### Exercise 54:
Compute the inverse of a 2x2 NumPy matrix.

```python
# Exercise 54
```

---

### Exercise 55:
Create a NumPy array of 10 random values and standardize it (mean 0, variance 1).

```python
# Exercise 55
```

---

### Exercise 56:
Perform element-wise addition and subtraction on two NumPy arrays.

```python
# Exercise 56
```

---

### Exercise 57:
Create a NumPy array of random values and find the maximum element's index.

```python
# Exercise 57
```

---

### Exercise 58:
Create a 3x3 NumPy array and rotate it by 90 degrees.

```python
# Exercise 58
```

---

### Exercise 59:
Compute the Frobenius norm of a matrix.

```python
# Exercise 59
```

---

### Exercise 60:
Create a 3D NumPy array and slice out a subarray.

```python
# Exercise 60
```

---